- name: Log Ansible version
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Ansible version
      ansible.builtin.command: ansible --version
      register: ansible_output

    - name: Set JSON output variable
      ansible.builtin.set_fact:
        json_output: "{{ ansible_output.stdout | to_nice_json(indent=2) }}"

    - name: Set log message
      ansible.builtin.set_fact:
        log_message:
          - "Ansible version: {{ ansible_output.stdout }}"
          - "Logged by: {{ lookup('env', 'USER') }}"
          - "JSON Output: | {{ json_output }}"

    - name: Display log messages
      ansible.builtin.debug:
        msg: "{{ log_message }}"
