- name: Log Ansible version
  hosts: all
  gather_facts: true
  tasks:
    - name: Display {{ tower_job_id }}
      ansible.builtin.debug:
        msg: '{{ {{ tower_job_id }}  }}'

    - name: Display {{ awx_job_id }}
      ansible.builtin.debug:
        msg: '{{ {{ awx_job_id }}  }}'
